all:
	cargo build --release -Z unstable-options --out-dir .
install:
	# Could have done this but let's use debian/install
	#install -d $(DESTDIR)/usr/bin
	#install -m0755 ff $(DESTDIR)/usr/bin/findfiles
	mv ff findfiles
